<?xml version="1.0" ?>
<!--Multicorp Input File-->
<?xml-stylesheet type="text/xsl" href="multicorp_default_input.xsl" ?>
<!DOCTYPE MulticorpDefaultInput[
  <!ELEMENT MulticorpDefaultInput ANY>
  <!ELEMENT Model ANY>
  <!ELEMENT Note ANY>
  <!ELEMENT CorrosionCase ANY>
  <!ELEMENT Composition ANY>
  <!ELEMENT FlowModel ANY>
  <!ELEMENT Parameter ANY>
  <!ELEMENT VaryingParameter ANY>
  <!ELEMENT ParamGroup ANY>
  <!ELEMENT ParamGroupDef ANY>
  <!ELEMENT ParamTable ANY>
  <!ELEMENT ParamRow ANY>
  <!ATTLIST Model name ID #REQUIRED>
  <!ATTLIST Parameter name ID #REQUIRED>
  <!ATTLIST VaryingParameter name ID #REQUIRED>
  <!ATTLIST ParamGroup name ID #REQUIRED>
  <!ATTLIST ParamGroupDef name ID #REQUIRED>
  <!ATTLIST ParamTable name ID #REQUIRED>
  <!ATTLIST ParamRow name ID #REQUIRED>
  <!ATTLIST ParamRowDef name ID #REQUIRED>
]>

<!--default display units (the first in list of units in Unit.vb)
  LENGTH=METER
  TEMPERATURE=CELSIUS
  PRESSURE=BAR
  VELOCITY=METER_PER_SECOND
  PERCENT=%
  ROTATIONAL_VELOCITY=/min
  time_units=MINUTE
  GAS_CONCENTRATION_units=PERCENTAGE
  gas_flow_rate_units=STANDARD_METER_3_PER_DAY
  liquid_flow_rate_units=METER_3_PER_DAY
  WATER_SPEC_CONCENTRATION=PPMW
  viscosity_units=PAS
  density_units=KG_PER_CUBIC_METER
  TENSION=NEWTON_PER_METER
  FREQUENCY=/min
  freq_units=TIMES_PER_MINUTE
  ANGLE=DEGREE
  HEAT_CAPACITY=J_KG_K
  roughness_units=
  conductivity_units=W_M_K
  condensation_rate_units=ML_MSQUARE_S

base units
            LENGTH.baseUnit=Unit.METER
            CONTROL_LENGTH.baseUnit=Unit.PIXEL
            TEMPERATURE.baseUnit=Unit.CELSIUS
            PRESSURE.baseUnit=Unit.BAR
            VELOCITY.baseUnit=Unit.METER_PER_SECOND
            PERCENT.baseUnit=Unit.FRACTION
            ROTATIONAL_VELOCITY.baseUnit=Unit.RevolutionsperMinute
            TIME.baseUnit=Unit.HOUR
            NULLTYPE.baseUnit=Unit.NULL
            GAS_CONCENTRATION.baseUnit=Unit.BAR
            CONCENTRATION.baseUnit=Unit.PPMW
            VISCOSITY.baseUnit=Unit.PAS
            GAS_FLOW_RATE.baseUnit=Unit.STANDARD_METER_3_PER_DAY
            LIQUID_FLOW_RATE.baseUnit=Unit.METER_3_PER_DAY
            DENSITY.baseUnit=Unit.KG_PER_CUBIC_METER
            TENSION.baseUnit=Unit.NEWTON_PER_METER
            FREQUENCY.baseUnit=Unit.TIMES_PER_MINUTE
            ANGLE.baseUnit=Unit.DEGREE
            HEAT_CAPACITY.baseUnit=Unit.J_KG_K
            CONDUCTIVITY.baseUnit=Unit.W_M_K
            CORROSION_RATE.baseUnit=Unit.MM_PER_YEAR
            CONDENSATION_RATE.baseUnit=Unit.ML_MSQUARE_S

            INTERVAL_AS_LOOPS.baseUnit=Unit.LOOPS
            INTERVAL_AS_MILLISECONDS.baseUnit=Unit.MILLISECONDS
            INTERVAL_AS_POINTS.baseUnit=Unit.POINTS

            PPMVUNIT.baseUnit=Unit.PPMV

            STRESS.baseUnit=Unit.PA

  -->
<MulticorpDefaultInput>
  <Model name="CorrosionCase"
         assembly="mc-corrosioncase, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null"
         className="edu.ohiou.icmt.multicorp.corrcase.CorrosionCase"
         ribbonTabName="General Input"
         processNodeName="Set General Input"
         displayName="General Input" helpName="GeneralInput" >
    <Description name="CorrosionCaseDescription" >This is the full list of general input parameters.</Description>
    <Note>Enter Note here...</Note>
    <Parameter name="Temperature" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
               toolTips="Bulk system temperature"
               defaultValue="25" displayOrder="2" softLimit="1 250" hardLimit="0 300"
               unitType="TEMPERATURE" units="temperature_units" />
    <Parameter name="Total Pressure" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
               toolTips="Total pressure of the system.\n
                        If the exact pressure is unknown, a suggested pressure is 10% greater than the sum of the known partial pressures."
               defaultValue="10" displayOrder="4" softLimit="1 200" hardLimit="0 300"
               unitType="PRESSURE" units="pressure_units" />
    <Parameter name="Steel Type" defaultSelection="0" className="edu.ohiou.icmt.modeling.param.OptionParameter"
               displayOrder="5" options="STEEL_TYPE_OPTIONS" enabled="false" />
			   <Parameter name="Corrosion Type" defaultSelection="0" className="edu.ohiou.icmt.modeling.param.OptionParameter"
               toolTips="Select:\n
                        BLC - bottom of line corrosion\n
                        TLC - top of the line corrosion (Company must be a sponsor of TLC research to use TLC option.)"
               displayOrder="6" options="CORROSION_TYPE_OPTIONS" />
    <Parameter name="Flow Type" defaultSelection="0" className="edu.ohiou.icmt.modeling.param.OptionParameter"
               toolTips="Select flow type:\n
                        Single phase: water flow\n
                        Two phase: oil/water flow or gas/water flow\n
                        Three phase: gas/oil/water flow"
               displayOrder="8" options="FLOW_TYPE_OPTIONS" />
    <Parameter name="Simulation Engine" defaultSelection="0" className="edu.ohiou.icmt.modeling.param.OptionParameter"
               toolTips="Select simulation engine:\n
                        Multicorp: point model/parametric run/ line run\n
                        Freecorp: transient simulation/ steady state simulation"
               displayOrder="9" options="SIMU_ENGINE_OPTIONS" />			   
    <Parameter name="Simulation Type" defaultSelection="0" className="edu.ohiou.icmt.modeling.param.OptionParameter"
               toolTips="Select simulation type:\n
                        Point Model - simulates corrosion rate at a single location;\n
                        Parametric Run - allows variation of selected inputs to run independent Point Model calculations;\n
                        Line Run - uses input line information to run a series of Point Model calculations."
               displayOrder="10" options="FREECORP_OPTIONS" />
    <Parameter name="Language" defaultSelection="0" className="edu.ohiou.icmt.modeling.param.OptionParameter"
               toolTips="Language for which format will be used to store model in input file.\n
                        Currently stores only numbers in selected format.\n
                        Parameter names are still in english."
               displayOrder="1"
               options="LANGUAGE_OPTIONS" />


    <!--Free Composition Model-->
    <Model name="FreeComposition"
           assembly="fc-composition, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
           className="edu.ohiou.icmt.freecorp.composition.FreeCompositionModel"
           ribbonTabName="Composition"
           processNodeName="Set Composition Data" helpName="Composition" >
      <Note>Enter Note here...</Note>
      <!--A group panel can be generated without title bar. -->

      <!-- 
    Bruce Brown - 20130504  modified significant digits and tool tips 
    Bruce Brown - addition of lower limit for pH2S is due to significant increase in calculation time when pH2S is lower than 0.0001 bar.
    -->
      <!-- Column 1 of Composition -->
      <ParamGroup name="CompoCol1" isTitleVisible="false" displayOrder="1">
        <!-- Gas composition group -->
        <ParamGroup name="Gas content" displayOrder="1">
          <Parameter name="H2S Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                     toolTips="Partial pressure or mol percent of hydrogen sulfide.
                              Recommended limits: pH2S greater than 0.0001 bar, but less than 1 bar."
                     displayOrder="2" defaultValue="0" softLimit="0 1" hardLimit="0 5" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="CO2 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                     toolTips="Partial pressure or mol percent of carbon dioxide."
                     displayOrder="1" defaultValue="1" softLimit="0.1 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="N2 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure or mol percent of nitrogen.\n Used to balance total pressure as it has no effect on corrosion rate."
                     displayOrder="3" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" isOutput="true" />
          <Parameter name="HAc Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure or mol percent of acetic acid."
                     displayOrder="4" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="H2O Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="The partial pressure of water vapor is directly related to the temperature and cannot be adjusted by the user.\n
                              pH2O(bar)=EXP(73.649 - 7258.2/Tk - 7.3037*LN(Tk) + 0.0000041653*(Tk)^2)/100000\n
                              Perry's 7th Ed., p2-54, Table 2-6"
                     displayOrder="5" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" isOutput="true" />
        </ParamGroup>

        <!--Hydrocarbon composition group-->
        <ParamGroup name="Hydrocarbon content" displayOrder="2" >
          <Parameter name="CH4 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of methane."
                     displayOrder="1" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C2H6 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of ethane."
                     displayOrder="2" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C3H8 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of propane."
                     displayOrder="3" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C4H10 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of butane."
                     displayOrder="4" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C5H12 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of pentane."
                     displayOrder="5" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C6H14 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of hexane."
                     displayOrder="6" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C7H16 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of heptane."
                     displayOrder="7" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
          <Parameter name="C8H18 Gas Content" className="edu.ohiou.icmt.modeling.param.Parameter"
                     toolTips="Partial pressure of octane."
                     displayOrder="8" defaultValue="0" softLimit="0 25" hardLimit="0 215" significantDigits="3"
                     unitType="GAS_CONCENTRATION" units="gas_concentration_units" dependency="Total Pressure" />
        </ParamGroup>

      </ParamGroup>

      <!-- Column 2 of Composition -->
      <ParamGroup name="CompoCol2" isTitleVisible="false" displayOrder="2">

        <!-- Aqueous Species -->
        <ParamGroup name="Aqueous Species" className="edu.ohiou.icmt.modeling.globalresources.WaterSpecs"
                    displayOrder="1" flowDirection="1" >

          <!-- Column 1 of Aqueous Species -->
          <ParamGroup name="Aqueous_Col_1" isTitleVisible="false" displayOrder="1" >

            <!--ph model group-->
            <ParamGroup name="pH Model" disPlayName="pH" displayOrder="1">
              <Parameter name="pH Calculation" className="edu.ohiou.icmt.modeling.param.OptionParameter" defaultSelection="1"
                         displayOrder="1" options="PH_TYPE_OPTIONS" isVisible="true"/>
              <Parameter name="pH" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                         toolTips="Bulk pH value after saturation of soluble gases into water composition."
                         displayOrder="2" defaultValue="4" softLimit="3 7" hardLimit="2 9"
                         significantDigits="3"
                         unitType="NULLTYPE" units="ph_units" />
            </ParamGroup>

            <ParamGroup name="CO2 Species" displayOrder="2" >
              <Parameter name="CO2" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Aqueous concentration of carbon dioxide."
                         displayOrder="3" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration" saveResult="true"/>
              <Parameter name="H2CO3" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Concentration of carbonic acid in solution."
                         displayOrder="4" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" saveResult="true"/>
              <Parameter name="HCO3-" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                         toolTips="Concentration of bicarbonate in solution."
                         displayOrder="5" defaultValue="9.058" softLimit="0 12240" hardLimit="0.000001 225000"
                         significantDigits="6"
                         unitType="CONCENTRATION" units="water_spec_concentration" saveResult="true"/>
              <Parameter name="CO32-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Concentration of carbonate ion in solution."
                         displayOrder="6" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" saveResult="true"/>
            </ParamGroup>

            <ParamGroup name="HAc Species" displayOrder="3" >
              <Parameter name="HAc" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Concentration of free acetic acid in solution."
                         displayOrder="8" defaultValue="0" softLimit="0 1000" hardLimit="0 10000000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutPut="true" />
              <Parameter name="Ac-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Concentration of acetate in solution."
                         displayOrder="9" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutPut="true" />
              <Parameter name="Total HAc+Ac" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                         toolTips="Bulk concentration of total acetic acid in solution (HAc + Ac-)."
                         displayOrder="22" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="6"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
            </ParamGroup>

            <ParamGroup name="H2S Species" displayOrder="4" >
              <Parameter name="H2S" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of aqueous hydrogen sulfide [H2S(aq)]."
                         displayOrder="10" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="HS-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of bisulfide."
                         displayOrder="11" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" />
              <Parameter name="S2-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of sulfide ion."
                         displayOrder="12" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" />
              <Parameter name="H2S+HS+S" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Concentration of total sulfides in solution [H2S(aq) + HS + S2-]."
                         displayOrder="21" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" />
            </ParamGroup>

          </ParamGroup>

          <!-- Column 2 of Aqueous Species -->
          <ParamGroup name="Aqueous_Col_2" isTitleVisible="false" displayOrder="2" >
            <ParamGroup name="Other Brine Species" displayOrder="2" >
              <Parameter name="H+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of hydrogen ions."
                         displayOrder="1" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" saveResult="true"/>
              <Parameter name="Fe2+" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                         toolTips="Bulk concentration of ferrous ions."
                         displayOrder="2" defaultValue="1" softLimit="0 100" hardLimit="0 1000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration" saveResult="true"/>
              <Parameter name="Na+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of sodium ions."
                         displayOrder="13" defaultValue="0.286" softLimit="0 77000" hardLimit="0 200000"
                         significantDigits="6"
                         unitType="CONCENTRATION" units="water_spec_concentration" saveResult="true"/>
              <Parameter name="Ca2+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of calcium ions."
                         displayOrder="15" defaultValue="0" softLimit="0 1000" hardLimit="0 2000"
                         significantDigits="4"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="Ba2+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of barium ions."
                         displayOrder="16" defaultValue="0" softLimit="0 10" hardLimit="0 1000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="K+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of potassium ions."
                         displayOrder="17" defaultValue="0" softLimit="0 500" hardLimit="0 1000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="Mg2+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of magnesium ions."
                         displayOrder="19" defaultValue="0" softLimit="0 2500" hardLimit="0 3500"
                         significantDigits="4"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="Sr2+" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of strontium ions."
                         displayOrder="20" defaultValue="0" softLimit="0 30" hardLimit="0 1000000"
                         significantDigits="6"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="Cl-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of chloride ions."
                         displayOrder="21"  defaultValue="1.17E-5" softLimit="0 120000" hardLimit="0 200000"
                         significantDigits="6"
                         unitType="CONCENTRATION" units="water_spec_concentration" saveResult="true"/>
              <Parameter name="SO42-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of sulfate ions."
                         displayOrder="22" defaultValue="0" softLimit="0 3000" hardLimit="0 96330"
                         significantDigits="5"
                         unitType="CONCENTRATION" units="water_spec_concentration" />
              <Parameter name="OH-" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of hydroxide ions."
                         displayOrder="23" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         isOutput="true" saveResult="true"/>
              <Parameter name="NaCl" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of NaCl."
                         displayOrder="24" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         saveResult="true"/>
              <Parameter name="O2" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Bulk concentration of Oxygen."
                         displayOrder="25" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="CONCENTRATION" units="water_spec_concentration"
                         saveResult="true"/>              
              <Parameter name="Ionic Strength" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Ionic strength of the bulk solution"
                         displayOrder="26" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         unitType="NULLTYPE" units="ph_units" significantDigits="3"
                         isOutput="true" />
              <Parameter name="Alkalinity" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Equivalent bicarbonate balance"
                         displayOrder="28" defaultValue="0" softLimit="-100 100"
                         significantDigits="2"
                         unitType="ALKALINITY_TYPE" units="alkalinity_units"
                         isOutput="true" />
            </ParamGroup>

          </ParamGroup>

          <!-- Column 3 of Aqueous Species -->
          <ParamGroup name="Aqueous_Col_3" isTitleVisible="false" displayOrder="3" >

            <ParamGroup name="Saturation Level" displayOrder="4" >
              <Parameter name="FeCO3 Saturation Level" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Saturation level of iron carbonate:
                              S(FeCO3)=[Fe2+][CO32-]/Ksp(FeCO3)"
                         displayOrder="1" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="NULLTYPE" units="no_units"
                         isOutput="true" />
              <Parameter name="CaCO3 Saturation Level" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Saturation level of calcium carbonate:
                              S(CaCO3)=[Ca2+][CO32-]/Ksp(CaCO3)"
                         displayOrder="2" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="NULLTYPE" units="no_units"
                         isOutput="true" />
              <Parameter name="CaSO4 Saturation Level" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Saturation level of calcium sulfate:
                              S(CaSO4)=[Ca2+][SO42-]/Ksp(CaSO4)"
                         displayOrder="3" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="NULLTYPE" units="no_units"
                         isOutput="true" />
              <Parameter name="FeS Saturation Level" className="edu.ohiou.icmt.modeling.param.Parameter"
                         toolTips="Saturation level of iron sulfide:
                              S(FeS)=[Fe2+][S2-]/Ksp(FeS)mackinawite"
                         displayOrder="4" defaultValue="0" softLimit="0 1000000" hardLimit="0 1000000"
                         significantDigits="3"
                         unitType="NULLTYPE" units="no_units"
                         isOutput="true" />
            </ParamGroup>

          </ParamGroup>

        </ParamGroup>

      </ParamGroup>

    </Model>

    <!--Free Flow Model-->
    <Model name="FreeFlowModel"
           assembly="fc-flow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
           className="edu.ohiou.icmt.freecorp.flow.FreeFlowModel"
           displayName="Water Flow" >
      <Note>Enter Note here...</Note>
      <!-- start flow columns -->
      <!-- flow column 1 -->
      <ParamGroup name="flowCol1" isTitleVisible="false" displayOrder="1" flowDirection="0" >

        <ParamGroup name="Flow Velocity" displayOrder="2" >
          <Parameter name="Superficial Water Velocity" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                     toolTips="Vsl - the hypothetical fluid velocity calculated as if water was the only phase filling the cross sectional area."
                     displayOrder="2" defaultValue="0.2" softLimit="0.01 10" hardLimit="0 300" unitType="VELOCITY" units="velocity_units" />
          <Parameter name="Superficial Gas Velocity" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                     toolTips="Vsg - a hypothetical gas velocity calculated as if gas was the only phase filling the cross sectional area."
                     displayOrder="4" defaultValue="2" softLimit="0.1 100" hardLimit="0 300" unitType="VELOCITY" units="velocity_units" />
          <Parameter name="Superficial Oil Velocity" className="edu.ohiou.icmt.modeling.param.Parameter" isParametric="true"
                     toolTips="Vso - a hypothetical fluid velocity calculated as if oil was the only phase filling the cross sectional area."
                     displayOrder="3" defaultValue="0.8" softLimit="0.01 10" hardLimit="0 300" unitType="VELOCITY" units="velocity_units" />
          <Parameter name="Input Type" className="edu.ohiou.icmt.modeling.param.OptionParameter"
                     toolTips="Choose the preferred input:\n
                              - flow velocity or\n
                              - volumetric flow rate."
                     displayOrder="0" defaultSelection="0" options="INPUT_TYPE_OPTIONS" />
          <Parameter name="Velocity Input Type" className="edu.ohiou.icmt.modeling.param.OptionParameter"